# Site settings
title: Making Changes, One Variable at a time
header-img: img/home-bg.png
email: hui1021@gmail.com
copyright_name: hannah11361
description: > # this means to ignore newlines until "baseurl:"
  Journey Through Codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hannah11361
learn_profile: hannah11361
email_username: hui1021@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
